# Generated by Django 6.1.1 on 2026-09-12 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='skills_required',
            field=models.CharField(blank=True, default='', help_text='Required skills or technologies, comma-separated (e.g. Python, ROS, Figma)', max_length=255),
        ),
    ]
