# Generated by Django 6.1.1 on 2026-09-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projectmembership_projectteam_projectmembership_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.DecimalField(decimal_places=2, help_text='Budget in Bangladeshi Taka (BDT)', max_digits=10),
        ),
    ]
