# Generated by Django 6.1 on 2026-09-11 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. I will design professional event posters for your RUET club', max_length=200)),
                ('description', models.TextField(help_text='Describe the scope, deliverables, and what clients should expect.')),
                ('category', models.CharField(choices=[('Web Development', 'Web Development'), ('Programming', 'Programming & Software'), ('App Development', 'App Development'), ('Graphic Design', 'Graphic Design'), ('UI/UX Design', 'UI/UX Design'), ('Embedded Systems', 'Embedded Systems & IoT'), ('Electronics', 'Electronics & Hardware'), ('CAD & Engineering', 'CAD & Engineering Modeling'), ('Writing', 'Technical Writing & Documentation'), ('Video Editing', 'Video Editing & Media'), ('Photography', 'Campus Photography'), ('Tutoring', 'Academic Tutoring'), ('Research', 'Research Assistance'), ('Other', 'Other Services')], default='Web Development', max_length=50)),
                ('skills', models.CharField(blank=True, help_text='Relevant tools or technologies, comma-separated (e.g. React, Tailwind, Figma)', max_length=255)),
                ('delivery_time_days', models.PositiveIntegerField(default=3, help_text='Expected delivery time in days')),
                ('price_estimate', models.DecimalField(blank=True, decimal_places=2, help_text='Optional starting price or estimated budget in USD', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Toggle service availability in the marketplace')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
