# Generated by Django 6.1.1 on 2026-09-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price_estimate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional starting price or estimated budget in Bangladeshi Taka (BDT)', max_digits=10, null=True),
        ),
    ]
