# Generated by Django 6.1.1 on 2026-09-22 15:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_department_user_github_url_user_linkedin_url_and_more'),
        ('projects', '0005_alter_project_budget'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(help_text='Rating score from 1 to 5 stars.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(help_text='Review feedback and remarks.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(help_text='The completed project this review is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='projects.project')),
                ('reviewed_user', models.ForeignKey(help_text='User receiving the review.', on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(help_text='User submitting the review.', on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('project', 'reviewer', 'reviewed_user'), name='unique_project_review_pair'), models.CheckConstraint(condition=models.Q(('reviewer', models.F('reviewed_user')), _negated=True), name='prevent_self_review')],
            },
        ),
    ]
