# Generated by Django 6.1.1 on 2026-09-17 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_message', 'New message'), ('new_application', 'New application'), ('application_accepted', 'Application accepted'), ('application_rejected', 'Application rejected'), ('team_added', 'Added to team'), ('project_started', 'Project started'), ('project_completed', 'Project completed'), ('project_closed', 'Project closed')], max_length=30),
        ),
    ]
