# Generated by Django 6.1.1 on 2026-10-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_message', 'New message'), ('new_application', 'New application'), ('application_accepted', 'Application accepted'), ('application_rejected', 'Application rejected'), ('team_added', 'Added to team'), ('project_started', 'Project started'), ('project_completed', 'Project completed'), ('project_closed', 'Project closed'), ('new_review', 'New review')], max_length=30),
        ),
    ]
